### PR TITLE
Add ability set integer color for background. fix #360

### LINKED ISSUE #360: Change background color for date
How to change background color for date? I know about `caldroidFragment.setBackgroundResourceForDate(R.color.blue, mDate)` but it use resource, I want just color in hex or integer presentation, like `caldroidFragment.setBackgroundColorForDate(0xFF00FF00, mDate)` for green background

### PR DESCRIPTION
**Pull request by dexion**

### CODE REVIEW

**Comment by nick11roberts** [comment]
Please roomorama, merge this. You're our only hope.

**Comment by thomasdao** [comment]
Thanks for the PR :). Btw what's the chance that Android compiler will compile a background resource to the same integer with color integer? Will it make the behavior less predictable? I'm thinking whether a new method should be added instead of using setBackgroundResourceForDate

**Comment by thomasdao** [comment]
@nick11roberts and @dexion in latest Caldroid 3.0.0, the "setBackgroundResource*" methods have been replaced by "setBackgroundDrawable*" methods, where you can provide a drawable for certain dates instead of having to define static resource. It should be more flexible, for example if you want dynamic color, you can use ColorDrawable. Let me know if it works in your case :)

**Comment by nick11roberts** [comment]
That's awesome! Thanks!

**Pull request merged**
